name: Blog CI/CD

# 权限配置，部署时需要用到github token，需要配置权限，否则会报错
#permissions:
#contents: write
on:
    push:
        branches:
            - master # 只在master上push触发部署
        paths-ignore: # 下列文件的变更不触发部署，可以自行添加
            - README.md
            - LICENSE

jobs:
    build-production:
        runs-on: ubuntu-latest # 使用ubuntu系统镜像运行自动化脚本(温馨提示：和你所使用的操作系统及服务器系统无关，我本地用的windows10,云服务器用的centos)
        strategy:
            matrix:
                node-version: '20.18.2' # 配置所需node版本
        steps: # 自动化步骤
            - uses: actions/checkout@v2 # 第一步，检出仓库副本

            - name: Use Node.js ${{ matrix.node-version }} #规定node.js版本(可不配置)
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Install dependencies # 第二步，安装依赖
              run: npm install

            - name: Build # 第三步，打包代码
              run: npm run build --if-present

            - name: Deploy to Server # 第四步，rsync推送文件
              uses: AEnterprise/rsync-deploy@v1.0 # 使用别人包装好的步骤镜像
              with:
                  folder: dist # 操作应该部署的文件夹。
                  # 提交分支名
                  branch: static-pages
                  TARGET_FOLDER: / # 打包的文件将放到静态服务器 / 目录下
                  REPOSITORY_NAME: ao-er-mjz/websiteRecord-pages # 这是我的 github page 仓库
